### ISSUE TITLE
Failed to start the Kernel

### ISSUE THREAD

**Issue by Chen-tao** [ipython-books/cookbook-code#26]
when i start notebook, there's a error in my console as follow
![image](https://cloud.githubusercontent.com/assets/1845119/10410780/83fdcc0a-6f7e-11e5-870a-cb1ccf4ab3b0.png)

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/notebook/base/handlers.py", line 437, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Library/Python/2.7/site-packages/notebook/services/sessions/handlers.py", line 56, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/Library/Python/2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/Library/Python/2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
    **kwargs)
  File "/Library/Python/2.7/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "/Library/Python/2.7/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    **kw)
  File "/Library/Python/2.7/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Library/Python/2.7/site-packages/jupyter_client/launcher.py", line 124, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

how can I fix it ?

my mac's info:

![image](https://cloud.githubusercontent.com/assets/1845119/10410769/54bb56b0-6f7e-11e5-9f0d-7a5bb16e1ac4.png)

**Comment by rossant** [comment]
It looks like this is using the default OS X Python. I would recommend to use Anaconda instead - you can download it here and follow the installation instructions: https://www.continuum.io/downloads

**Comment by Chen-tao** [comment]
OK, I use Anaconda solve it.
